version: '2'
services:
    data:
        image: silintl/data-volume:latest
        volumes:
            - ./application:/data

    db:
        image: silintl/mariadb:latest
        ports:
            - "3306"
        env_file:
            - ./local.env

    app:
        build: ./
        volumes_from:
            - data
        ports:
            - "8080:80"
        depends_on:
            - db
        env_file:
            - ./local.env

    cli:
        image: silintl/php7:latest
        volumes_from:
            - data
        working_dir: /data
        env_file:
            - ./local.env
        command: ["true"]

    test:
        image: silintl/php7:latest
        volumes_from:
            - data
        working_dir: /data
        depends_on:
            - app
        env_file:
            - ./local.env
        environment:
            APP_ENV: test
        command: ./run-tests.sh
