name: Test and Publish

on:
  push:
    branches: [ 'main' ] #Triger on the main branch
    tags: [ '[0-9]+.[0-9]+.[0-9]+' ]  # Trigger on version tags like '0.1.0'

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run unit tests
        run: docker compose -f actions-services.yml run --rm app ./run-tests.sh
      - name: Run API tests
        run: docker compose -f actions-services.yml run --rm app ./run-tests-api.sh
      - name: Check PSR2
        run: docker compose -f actions-services.yml run --rm app ./check-psr2.sh

  build-and-publish:
    name: Build and Publish Docker image 
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
           ${{ vars.DOCKER_ORG }}/${{ github.event.repository.name }}
           ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch  # Tag with branch name
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
